config/routes.rb
Rails.application.routes.draw do
  resources :aws
  get 'aws/download/:id' => 'aws#download'

end

app/models/aw.rb
class Aw < ActiveRecord::Base
  has_attached_file :uploaded_file, s3_protocol: :https, s3_permissions: :private
  validates_attachment_content_type :uploaded_file, content_type: /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/aws_controller.rb
class AwsController < ApplicationController
  before_action :set_aw, only: [:show, :edit, :update, :destroy]

  # GET /aws
  # GET /aws.json
  def index
    @aws = Aw.all
  end

  # GET /aws/1
  # GET /aws/1.json
  def show
  end

  # GET /aws/new
  def new
    @aw = Aw.new
  end

  # GET /aws/1/edit
  def edit
  end

  # POST /aws
  # POST /aws.json
  def create
    file_info = aw_params[:file]

    # file_directory = '/Users/ironyard/crg/aws/public/craig/'
    # new_file_path = file_directory + file_info.original_filename
    # File.open(new_file_path, "wb")  do |f|
    #   f.write(file_info.tempfile.read)
    # end



    @aw = Aw.new(aw_params)
    #@aw.update_attribute(:file, new_file_path)

    respond_to do |format|
      if @aw.save
        format.html { redirect_to @aw, notice: 'Aw was successfully created.' }
        format.json { render :show, status: :created, location: @aw }
      else
        format.html { render :new }
        format.json { render json: @aw.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aws/1
  # PATCH/PUT /aws/1.json
  def update
    respond_to do |format|
      if @aw.update(aw_params)
        format.html { redirect_to @aw, notice: 'Aw was successfully updated.' }
        format.json { render :show, status: :ok, location: @aw }
      else
        format.html { render :edit }
        format.json { render json: @aw.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aws/1
  # DELETE /aws/1.json
  def destroy
    @aw.destroy
    respond_to do |format|
      format.html { redirect_to aws_url, notice: 'Aw was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    aws_file = Aw.find(params[:id])
    aws_downloaded_file = Paperclip.io_adapters.for(aws_file.uploaded_file)

    File.open(aws_downloaded_file.path, 'r') do |f|
      send_data(f.read,
                                                              :type => aws_file.uploaded_file_content_type,
                                                              :disposition => "inline",
                                                              :filename => aws_file.uploaded_file_file_name)
    end


    if File.exists?(aws_downloaded_file.path)
      File.delete(aws_downloaded_file.path)
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aw
      @aw = Aw.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aw_params
      params.require(:aw).permit(:file, :uploaded_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aws_helper.rb
module AwsHelper
end

app/views/aws/_form.html.erb
<%= form_for(@aw) do |f| %>
  <% if @aw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aw.errors.count, "error") %> prohibited this aw from being saved:</h2>

      <ul>
      <% @aw.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uploaded_file %><br>

    <%= f.file_field :uploaded_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aws/edit.html.erb
<h1>Editing Aw</h1>

<%= render 'form' %>

<%= link_to 'Show', @aw %> |
<%= link_to 'Back', aws_path %>

app/views/aws/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Aws</h1>

<table>
  <thead>
    <tr>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aws.each do |aw| %>
      <tr>
        <td><a href="<%= aw.uploaded_file %>"><%= aw.uploaded_file %></a></td>
        <td><%= link_to 'Show', aw %></td>
        <td><%= link_to 'Edit', edit_aw_path(aw) %></td>
        <td><%= link_to 'Destroy', aw, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aw', new_aw_path %>

app/views/aws/new.html.erb
<h1>New Aw</h1>

<%= render 'form' %>

<%= link_to 'Back', aws_path %>

app/views/aws/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File:</strong>
  <%= @aw.uploaded_file %>
</p>

<%= link_to 'Edit', edit_aw_path(@aw) %> |
<%= link_to 'Back', aws_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aws</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>